# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black .
        language: system
        require_serial: true
        pass_filenames: false
        always_run: true
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        pass_filenames: false
        always_run: true
    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        pass_filenames: false
        always_run: true
