name: "Run Command in Dev Container"
description: "Runs a command in the repo's Dev Container"
inputs:
  command:
    description: "Command to run"
    required: true
runs:
  using: "docker"
  image: "../../Dockerfile"
  entrypoint: "sh -c"
  args:
    - ${{ inputs.command }}
